### ISSUE TITLE
Cleanup pages

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#18]
* [ ] pages/docs/Adding-Real-Time-to-Django-Applications.md
* [ ] pages/docs/AngularJS-Application-Components.md
* [ ] pages/docs/Anonymous-Authentication.md
* [ ] pages/docs/Application-Scenarios.md
* [ ] pages/docs/Application-Templates.md
* [ ] pages/docs/Architecture.md
* [ ] pages/docs/Authentication.md
* [ ] pages/docs/Authorization.md
* [ ] pages/docs/Automatic-startup-and-restart.md
* [ ] pages/docs/Basic-Registrations.md
* [ ] pages/docs/Basic-Subscriptions.md
* [ ] pages/docs/Browser-Support.md
* [ ] pages/docs/Caller-Identification.md
* [ ] pages/docs/CGI-Script-Service.md
* [ ] pages/docs/Choose-your-Weapon.md
* [ ] pages/docs/Configuration-Overview.md
* [ ] pages/docs/Configuring-Crossbar.io's-Logging.md
* [ ] pages/docs/Connection-Pools.md
* [ ] pages/docs/Container-Configuration.md
* [ ] pages/docs/Contributing-to-the-project.md
* [ ] pages/docs/Controller-Configuration.md
* [ ] pages/docs/Cookie-Authentication.md
* [ ] pages/docs/Cookie-Tracking.md
* [ ] pages/docs/Crossbar-License.md
* [ ] pages/docs/Database-Integration.md
* [ ] pages/docs/Database-Programming-with-PostgreSQL.md
* [ ] pages/docs/Demo-Instance.md
* [ ] pages/docs/Documentation-License.md
* [ ] pages/docs/Endpoints.md
* [ ] pages/docs/Error-Handling.md
* [ ] pages/docs/Examples.md
* [ ] pages/docs/FAQ-Contributor-Assignment-Agreement.md
* [ ] pages/docs/FAQ.md
* [ ] pages/docs/Features.md
* [ ] pages/docs/File-Upload-Service.md
* [ ] pages/docs/Flash-Policy-Transports.md
* [ ] pages/docs/Getting-started-with-Cplusplus.md
* [ ] pages/docs/Getting-started-with-CSharp.md
* [ ] pages/docs/Getting-started-with-Erlang.md
* [ ] pages/docs/Getting-started-with-Java.md
* [ ] pages/docs/Getting-started-with-JavaScript-in-the-Browser.md
* [ ] pages/docs/Getting-started-with-NodeJS.md
* [ ] pages/docs/Getting-started-with-PHP.md
* [ ] pages/docs/Getting-started-with-Python.md
* [ ] pages/docs/Getting-started-with-Tessel.md
* [ ] pages/docs/Guest-Configuration.md
* [ ] pages/docs/Home.md
* [ ] pages/docs/How-Registrations-Work.md
* [ ] pages/docs/How-Subscriptions-Work.md
* [ ] pages/docs/HTTP-Bridge-Services-Callee.md
* [ ] pages/docs/HTTP-Bridge-Services-Caller.md
* [ ] pages/docs/HTTP-Bridge-Services-Publisher.md
* [ ] pages/docs/HTTP-Bridge-Services-Subscriber.md
* [ ] pages/docs/HTTP-Bridge-Services-Webhook.md
* [ ] pages/docs/HTTP-Bridge-Services.md
* [ ] pages/docs/Installation-from-Source.md
* [ ] pages/docs/Installation-guides-overview.md
* [ ] pages/docs/Installation-on-CentOS.md
* [ ] pages/docs/Installation-on-Docker.md
* [ ] pages/docs/Installation-on-FreeBSD.md
* [ ] pages/docs/Installation-on-Linux.md
* [ ] pages/docs/Installation-on-Mac-OS-X.md
* [ ] pages/docs/Installation-on-the-RaspberryPi.md
* [ ] pages/docs/Installation-on-Ubuntu-Snappy.md
* [ ] pages/docs/Installation-on-Ubuntu.md
* [ ] pages/docs/Installation-on-Windows.md
* [ ] pages/docs/Introduction.md
* [ ] pages/docs/IoT-Applications.md
* [ ] pages/docs/JavaScript-frameworks-and-libraries.md
* [ ] pages/docs/JSON-Value-Service.md
* [ ] pages/docs/Local-Installation.md
* [ ] pages/docs/Logging-in-Crossbar.io.md
* [ ] pages/docs/Management-API.md
* [ ] pages/docs/Manhole.md
* [ ] pages/docs/Mozilla-Persona.md
* [ ] pages/docs/Native-Worker-Shared-Options.md
* [ ] pages/docs/Network-Tuning.md
* [ ] pages/docs/Oracle-Database-Integration.md
* [ ] pages/docs/OTP-Authentication.md
* [ ] pages/docs/Pattern-Based-Registrations.md
* [ ] pages/docs/Pattern-Based-Subscriptions.md
* [ ] pages/docs/PostgreSQL-Integration-Publisher.md
* [ ] pages/docs/PostgreSQL-Integration.md
* [ ] pages/docs/Process-Environments.md
* [ ] pages/docs/Programming.md
* [ ] pages/docs/Progressive-Call-Results.md
* [ ] pages/docs/Project-Relations.md
* [ ] pages/docs/Publisher-Exclusion.md
* [ ] pages/docs/Publisher-Identification.md
* [ ] pages/docs/Quick-Start.md
* [ ] pages/docs/RawSocket-Transports.md
* [ ] pages/docs/Registration-Meta-Events-and-Procedures.md
* [ ] pages/docs/Reverse-Proxies.md
* [ ] pages/docs/Roadmap.md
* [ ] pages/docs/Router-Components.md
* [ ] pages/docs/Router-Configuration.md
* [ ] pages/docs/Router-Realms.md
* [ ] pages/docs/Router-Transports.md
* [ ] pages/docs/Running-on-privileged-ports.md
* [ ] pages/docs/Scaling-Crossbar.io.md
* [ ] pages/docs/Secure-WebSocket-and-HTTPS.md
* [ ] pages/docs/Security.md
* [ ] pages/docs/Session-Metaevents-and-Procedures.md
* [ ] pages/docs/Session-Metaevents.md
* [ ] pages/docs/Setup-in-the-Cloud.md
* [ ] pages/docs/Setup-on-Amazon-EC2.md
* [ ] pages/docs/Setup-on-Heroku.md
* [ ] pages/docs/Setup-on-Microsoft-Azure.md
* [ ] pages/docs/Shared-Registrations.md
* [ ] pages/docs/SSL-TLS-Interception-Proxies.md
* [ ] pages/docs/Starting-and-Stopping-Crossbar.io.md
* [ ] pages/docs/Static-Web-Service.md
* [ ] pages/docs/Stream-Testee.md
* [ ] pages/docs/Subscriber-Black-and-Whitelisting.md
* [ ] pages/docs/Subscription-Meta-Events-and-Procedures.md
* [ ] pages/docs/The-Command-Line.md
* [ ] pages/docs/Transports.md
* [ ] pages/docs/Try-out-without-Installation.md
* [ ] pages/docs/Updating-from-the-Repository.md
* [ ] pages/docs/URI-Format.md
* [ ] pages/docs/Using-Schemas.md
* [ ] pages/docs/Using-the-REST-to-WebSocket-Pusher.md
* [ ] pages/docs/WAMP-CRA-Authentication.md
* [ ] pages/docs/WAMP-Features.md
* [ ] pages/docs/WAMP-Long-Poll-Service.md
* [ ] pages/docs/Web-Redirection-Service.md
* [ ] pages/docs/Web-Transports-and-Services.md
* [ ] pages/docs/WebSocket-Compliance-Testing.md
* [ ] pages/docs/WebSocket-Compression.md
* [ ] pages/docs/WebSocket-Options.md
* [ ] pages/docs/WebSocket-Transports.md
* [ ] pages/docs/WSGI-Host-Service.md

**Comment by goeddea** [comment]
no info beyond a general "make documentation better"? not migrating to crossbario/crossbar with the docs
