### ISSUE TITLE
Document Cryptosign authentication

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#28]
migrated from https://github.com/crossbario/crossbar/issues/147

**Comment by goeddea** [comment]
Documentation for both Cookie and Ticket/OTP (which were referenced in the original issue) have been there for a while. 

What is missing is full documentation of Cryptosign authentication - so renaming to reflect this.

**Comment by goeddea** [comment]
migrated to https://github.com/crossbario/crossbar/issues/764
