### ISSUE TITLE
How to run on OpenShift

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#34]
migrated from https://github.com/crossbario/crossbar/issues/74

**Comment by jvdm** [comment]
I've managed to do something at https://github.com/jvdm/openshift-crossbar.

As soon as I get some time I will try to enable `wss`.

One thing that I'd like to ask you (and may the best place to do it would be the MLs) is if you have any suggestion or points to investigation as why openshift keeps returning a list of subprotocols in `sec-websocket-protocols` -- that is breaking the client (notice that they use a [websocket proxy](https://github.com/openshift/origin-server/tree/master/node-proxy)).

**Comment by oberstet** [comment]
@jvdm awesome! thanks!

rgd your Q: If openshift returns a list of subprotocols during the WebSocket opening handshake, they have a bug. This is non-conformant behavior vs RFC6455.

page 23:

```
/subprotocol/
          Either a single value representing the subprotocol the server
          is ready to use or null.  The value chosen MUST be derived
          from the client's handshake, specifically by selecting one of
          the values from the |Sec-WebSocket-Protocol| field that the
          server is willing to use for this connection (if any).
```

**Comment by oberstet** [comment]
rgd wss: is it possible to terminate the TLS in CB or will openshift force termination on the proxy and unwrap the TLS?

If the former is possible, you should be able to solve the issue above also, since the (broken) proxy cannot look into or fiddle with the traffic.

**Comment by oberstet** [comment]
I've skimmed over https://github.com/openshift/origin-server/tree/master/node-proxy .. I can't believe openshift is using such a crap;)

if they feel there is a need for proxying, they should use nginx. done.
