### ISSUE TITLE
Simple Python client to access the HTTP bridge

### ISSUE THREAD

**Issue by ericchapman** [crossbario/crossbardocs#42]
I am writing a small library for the HTTP bridge services (I was going to enhance crossbarconnect for you but it seems to have disappeared).  I am testing exception handling and I noticed that when I generate an exception in the registered procedure, the caller (using urllib2) hangs.

My code is on the develop branch at "https://github.com/thehq/python-crossbarhttp/tree/develop".  You'll see in "tests/crossbarhttp_tests.py" I have the last 2 tests commented out.  Those cause exceptions on the session side which cause the test to hang.

I believe XBAR should at least return a 500 or something rather than hang.  Thoughts?

**Comment by oberstet** [comment]
Yeah, sorry, we've moved the code from `crossbarconnect` to https://github.com/crossbario/crossbarexamples/tree/master/rest/needs_cleanup, as we thought it doesn't justify a own repo/project. This needs cleanup .. I don't know if it works right now ..

I think best would be to have these HTTP connect like enhancements as examples in

* crossbarexamples/rest/httpclient/python
* crossbarexamples/rest/httpclient/php

**Comment by oberstet** [comment]
hey, but I'd be fine pointing users to your repo/package/project (python-crossbarhttp) as well (rather than having it as an "example" in crossbarexamples) ..

**Comment by ericchapman** [comment]
@oberstet Thanks Tobias.  I am fine with that too.  It is basic but soon I will add auth and all of the other stuff.  I did notice the old XBAR connect was a little messy (no worries.  I know how it goes).  I'll get mine hooked up to CI and what not soon.

Just out of curiosity, I looked at the file "https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/rest/caller.py" and it looks like you guys are trying to handle the exceptions but I am just seeing a hang.  Any idea of the easiest way to debug that?

**Comment by oberstet** [comment]
What is XBAR? ;)

Sorry, I don't have time right now to look into this (my backlog is killing me), maybe @hawkowl can look, as she wrote most of the newer code in this area ..

**Comment by ericchapman** [comment]
@oberstet Haha.  My background is in hardware design and we always shortened it to "XBAR" in diagrams.  Force of habit I guess :).

No worries on being busy.  I'll take more of a look at it and see what @hawkowl Has to say whenever she gets to it.

**Comment by ericchapman** [comment]
@oberstet I spent a few hours cleaning up the library, adding key/secret, adding installation instructions, etc.  Feel free to point whoever to it.  The pypi package is "crossbarhttp".

**Comment by oberstet** [comment]
@hawkowl could you pls review above vs https://github.com/crossbario/crossbarexamples/tree/master/rest/needs_cleanup/python some time (not urgent). if it works with the REST bridge, maybe just kick our code and update the docs to hint users at Eric's lib?

**Comment by ericchapman** [comment]
@oberstet @hawkowl I actually figured out the error on this as well.  If I raise an exception with no text, it is causes the hang
```
    raise Exception()
```
Adding text fixed the issue.

**Comment by goeddea** [comment]
migrated to https://github.com/crossbario/crossbar/issues/763
