### ISSUE TITLE
ToCs for Subsections

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#43]
meejah 7:53 PM @oberstet: for crossbar.io/docs if it's possible, I think it would be nice to have the expanded ToC under "Administration" (or at least change the title to "Administration and Configuration"). I keep having to remind myself "config stuff" is under "administration"... 

This makes sense .. maybe even add ToCs for other subsections .. generally improve discoverability.

**Comment by goeddea** [comment]
migrated to https://github.com/crossbario/crossbar/issues/762
