### ISSUE TITLE
Complete systematic content structure

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#51]
Crossbar.io Documentation

- Background

- Installation

...

- Transports

- Web Services

- Security
  - Encryption
     - Transport encryption (TLS)
     - Payload encryption (WAMP-Cryptobox)

  - Authentication
     - Anonymous
     - Cookies (HTTP/WebSocket)
     - WAMP-Ticket
     - WAMP-CRA
     - WAMP-TLS
     - WAMP-Cryptosign

  - Authorization
     - Static authorization
     - Dynamic authorization
     - Database authorization (future)

- Production
  - Network tuning
  - OS integration
  - Crossbar.io DevOps Center

- Community

**Comment by goeddea** [comment]
migrated to https://github.com/crossbario/crossbar/issues/757
