### ISSUE TITLE
How to test app components and apps

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#60]
There were a couple of posts rgd how to test WAMP app components and whole apps on the mailing lists.

@ericchapman also published this:

https://medium.com/@theHQ/using-mock-and-trial-to-create-unit-tests-for-crossbar-applications-867e5b941cf2#.f0bsd2fio

We need a chapter in the programming guide ..

**Comment by goeddea** [comment]
migrated to https://github.com/crossbario/crossbar/issues/754
