### ISSUE TITLE
Document the new "disclose scheme"

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbardocs#68]
Generally, the new "URI namespace" configuration .. see also: https://github.com/crossbario/crossbar/issues/283

**Comment by goeddea** [comment]
Current "disclose" is documented in 

* http://crossbar.io/docs/Caller-Identification/
* http://crossbar.io/docs/Publisher-Identification/

Otherwise: Documentation is lagging behind regarding the new config for permissions + disclose.
